(()=>{
const esc=(v)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const list=(items)=>`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;
const cards=(items,cols="four")=>`<div class="pursuit-grid ${cols}">${items.map(x=>`<article class="pursuit-card"><span class="overline">${esc(x.tag)}</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join("")}</div>`;
const sectionHead=(kicker,title,intro)=>`<div class="pursuit-section-head"><div><div class="pursuit-kicker">${esc(kicker)}</div><h2>${esc(title)}</h2></div><p class="pursuit-section-intro">${esc(intro)}</p></div>`;
function visual(d){
 const nodes=(arr,cls)=>`<div class="${cls}">${arr.map((x,i)=>`<div class="visual-node"><b>${String(i+1).padStart(2,"0")}</b><strong>${esc(x[0])}</strong><small>${esc(x[1])}</small></div>`).join("")}</div>`;
 let body="",title="",caption="";
 if(d.visual==="journey"){title="From access leak to patient-journey control";caption="The account expands when each completed workflow carries context into the next one.";body=nodes([["Demand arrives","Calls, web, text, referrals"],["Intent resolved","Schedule, route, triage"],["Work orchestrated","Intake, insurance, tasks"],["Care advanced","Appointment and handoff"],["Journey continued","Follow-up, waitlist, payment"],["System learns","Memory, outcomes, protocols"]],"journey-line");}
 if(d.visual==="research"){title="From question to governed action";caption="Perplexity becomes harder to replace when trusted research is embedded in a recurring decision and its downstream work.";body=nodes([["Business question","A real decision with consequence"],["Evidence retrieval","Web, premium, internal"],["Cited synthesis","Multi-model comparison"],["Decision artifact","Recommendation, memo, analysis"],["Action layer","Comet, Computer, API"]],"research-line");}
 if(d.visual==="flywheel"){title="The continuous learning flywheel";caption="The moat compounds when research is connected to the decision and the outcome, not stored as an isolated transcript.";body=`<div class="flywheel">${[["Decision calendar","What must be learned and by when"],["Adaptive interviews","More depth and segment coverage"],["Decision-ready evidence","Patterns, contradictions, quotes"],["Outcome feedback","What changed and whether it worked"]].map((x,i)=>`<div class="visual-node"><b>${String(i+1).padStart(2,"0")}</b><strong>${esc(x[0])}</strong><small>${esc(x[1])}</small></div>`).join("")}</div>`;}
 if(d.visual==="stack"){title="The reliability control plane";caption="Evaluation is the reusable layer that can connect models, data, agents, experts, and production governance.";body=`<div class="stack-map">${[["BUSINESS OUTCOME","Uptime, quality, decision, safety, revenue","Executive consequence"],["AGENT OR APPLICATION","Tasks, tools, workflow state, escalation","End-to-end behavior"],["EVALUATION HARNESS","Datasets, rubrics, red teams, regression","Production gate"],["DATA + EXPERTISE","Real cases, domain judgment, feedback","Continuous improvement"],["MODELS + INFRASTRUCTURE","Frontier/open models, hosting, monitoring","Replaceable components"]].map(x=>`<div class="stack-layer"><b>${esc(x[0])}</b><span>${esc(x[1])}</span><small>${esc(x[2])}</small></div>`).join("")}</div>`;}
 if(d.visual==="lifecycle"){title="The customer-outcome expansion ladder";caption="Support is the land. Customer memory, action, and outcome pricing create expansion into the rest of the lifecycle.";body=nodes([["Consider","Questions and recommendations"],["Book or buy","Conversion and transactions"],["Prepare","Onboarding and proactive service"],["Resolve","Support and service recovery"],["Retain","Loyalty and save motions"],["Grow","Upsell, engagement, advocacy"]],"lifecycle-line");}
 if(d.visual==="ecosystem"){title="One field system across direct and partner routes";caption="The partnership is useful only when it changes customer access, technical delivery, field behavior, or economics.";body=`<div class="ecosystem-map"><div class="ecosystem-side"><div><b>DIRECT FIELD</b><span>Strategic accounts, industries, AI-native, startups</span></div><div><b>PRODUCT</b><span>Claude, Claude Code, API, agents, enterprise work</span></div><div><b>GOVERNANCE</b><span>Evals, security, usage economics, human boundaries</span></div></div><div class="ecosystem-core"><b>CONTROL POINT</b><strong>Governed production value</strong><span>One consequential workflow, one accountable owner, one deployment architecture, one expansion path.</span></div><div class="ecosystem-side"><div><b>CLOUDS</b><span>AWS, Google Cloud, Microsoft marketplaces and infrastructure</span></div><div><b>GSIs + ISVs</b><span>Implementation, industry workflows, tools, and distribution</span></div><div><b>DATA + CONTENT</b><span>Authoritative context and differentiated solutions</span></div></div></div>`;}
 if(d.visual==="sdlc"){title="From individual adoption to an agent-first SDLC";caption="The enterprise sale is won when daily developer value becomes an approved, measured, and repeatable organizational system.";body=nodes([["Plan","Issues, context, architecture"],["Build","Code, agents, migrations"],["Review","Humans, Bugbot, standards"],["Test","Quality, security, regression"],["Ship","PR, release, deployment"],["Learn","Metrics, patterns, expansion"]],"sdlc-line");}
 return `<div class="pursuit-visual"><div class="pursuit-visual-title"><strong>${esc(title)}</strong><span>${esc(caption)}</span></div>${body}</div>`;
}
function segments(d){return `<div class="segment-switcher" data-segment-switcher><div class="segment-buttons">${d.segments.map((s,i)=>`<button class="segment-button ${i===0?"active":""}" type="button" data-segment="${i}">${esc(s.label)}</button>`).join("")}</div>${d.segments.map((s,i)=>`<div class="segment-panel ${i===0?"active":""}" data-panel="${i}"><div><b>LAND</b><strong>${esc(s.wedge)}</strong></div><div><b>BUYER SYSTEM</b><strong>${esc(s.buyer)}</strong></div><div><b>VALUE</b><strong>${esc(s.value)}</strong></div><div><b>EXPAND</b><strong>${esc(s.expand)}</strong></div></div>`).join("")}</div>`;}
function renderPage(key,d){
 document.title=`${d.company} Growth Thesis | Connor Spiegelman`;
 const description=`A private public-information growth, account, partnership, and selling thesis for ${d.company}.`;
 const meta=document.querySelector('meta[name="description"]'); if(meta)meta.setAttribute("content",description);
 const subject=encodeURIComponent(`${d.company} interview — Connor Spiegelman`);
 return `<header class="pursuit-topbar"><div class="shell"><a class="pursuit-brand" href="index.html">CONNOR SPIEGELMAN<small>CI FLOW · PRIVATE PURSUIT</small></a><div class="pursuit-status">Public-information thesis<br>${esc(d.snapshot)}</div></div></header>
 <main>
 <section class="pursuit-hero shell"><div class="pursuit-role"><span>${esc(d.company)}</span><span>${esc(d.role)}</span><span>${esc(d.location)}</span></div><h1>${esc(d.headline).replace(/(not merely|not simply|not compete|not licenses|not another|not just)/i,"<em>$1</em>")}</h1><p class="pursuit-lead">${esc(d.lead)}</p><p class="pursuit-disclaimer">${esc(d.disclaimer)}</p><div class="pursuit-actions"><a href="#thesis">Read the thesis</a><a href="#account">See the target account</a><a href="#interview">Why I am pursuing the role</a></div><div class="signal-metrics">${d.signals.map(x=>`<div class="signal-metric"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join("")}</div></section>
 ${d.videoUrl?`<section class="pursuit-section shell"><div class="pursuit-kicker">THREE-MINUTE THESIS</div><div class="pursuit-visual"><iframe src="${esc(d.videoUrl)}" title="${esc(d.company)} commercial thesis video" allow="autoplay; fullscreen" allowfullscreen style="width:100%;aspect-ratio:16/9;border:0"></iframe></div></section>`:""}
 <section id="thesis" class="pursuit-section shell">${sectionHead("01 · COMPANY THESIS","How I see the business model and control point","I am looking for the point where product capability, customer economics, distribution, and future expansion reinforce one another.")}${cards(d.business,"four")}${visual(d)}</section>
 <section class="pursuit-section shell">${sectionHead("02 · MARKET CONTROL","Saturation, whitespace, and the market-takeover move","I would not attack every possible use case at once. I would identify where value is already proven, where competition is becoming interchangeable, and what new control point can compound.")}${cards(d.market,"three")}${segments(d)}</section>
 <section id="account" class="pursuit-section shell">${sectionHead("03 · ILLUSTRATIVE TARGET ACCOUNT",d.target.name,"A strategic-logo account lets me show how I would move from public signals to an account hypothesis, then replace assumptions through discovery.")}<div class="account-hero"><div class="account-label">WHY THIS ACCOUNT</div><h3>${esc(d.target.name)}</h3><p>${esc(d.target.context)}</p><div class="account-warning">${esc(d.target.warning)}</div></div><div class="pursuit-grid two"><article class="pursuit-card"><span class="overline">INITIAL WEDGE</span><h3>Start narrow enough to produce evidence.</h3><p>${esc(d.target.wedge)}</p></article><article class="pursuit-card"><span class="overline">COMMERCIAL RULE</span><h3>The first deployment must make expansion easier.</h3><p>Before proposing a pilot, I would identify the executive consequence, baseline, technical and human production gates, and the next adjacent workflow, team, site, or partner route.</p></article></div></section>
 <section class="pursuit-section shell">${sectionHead("04 · BUYING MAP","The organization that must agree","Complex enterprise sales are not one-buyer transactions. The commercial case must survive business, technical, risk, financial, and adoption scrutiny.")}<div class="buyer-map">${d.buyers.map(x=>`<div class="buyer"><b>${esc(x.type)}</b><strong>${esc(x.name)}</strong><p>${esc(x.text)}</p></div>`).join("")}</div></section>
 <section class="pursuit-section shell">${sectionHead("05 · VALUE MODEL","Translate capability into a defensible investment","The prospect’s most valuable business outcome should determine the value model. I would validate each variable rather than force a generic ROI calculator.")}<div class="value-formula"><div class="formula">${d.value.formula}</div><div class="value-levers">${d.value.levers.map(x=>`<div class="value-lever"><b>${esc(x.tag)}</b><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p></div>`).join("")}</div></div></section>
 <section class="pursuit-section shell">${sectionHead("06 · QUALIFICATION","What must be true before I call it real pipeline","Interest and a good demo are not enough. I want evidence that the account has consequence, ownership, feasibility, measurement, and an expansion path.")}<div class="qualification-list">${d.qualification.map((x,i)=>`<div class="qualification-item"><span>${String(i+1).padStart(2,"0")}</span><div><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p></div></div>`).join("")}</div></section>
 <section class="pursuit-section shell">${sectionHead("07 · PILOT TO PRODUCTION","Design the first deployment backward from scale","The pilot should answer a production decision. It should not become an isolated demonstration that requires a second sales cycle to create value.")}<div class="phase-grid">${d.phases.map((x,i)=>`<article class="phase"><div class="phase-no">PHASE ${String(i+1).padStart(2,"0")}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p>${list(x.items)}</article>`).join("")}</div></section>
 <section class="pursuit-section shell">${sectionHead("08 · OUTBOUND EXPERIMENT","Build pipeline and market intelligence together","A new BD motion should generate qualified opportunities and reveal which segment, workflow, buyer, trigger, message, and partner route actually converts.")}<div class="experiment"><div><h3>Experimental cohort</h3><p>${esc(d.outbound.cohort)}</p><h3>Hypotheses to test</h3>${list(d.outbound.hypotheses)}</div><div><h3>Account-based sequence</h3><div class="sequence">${d.outbound.sequence.map(x=>`<div class="sequence-step"><b>${esc(x.day)}</b><span>${esc(x.text)}</span></div>`).join("")}</div></div></div></section>
 <section class="pursuit-section shell">${sectionHead("09 · REVENUE ECOSYSTEM","Direct sales, partnerships, strategic options, and defense","I would optimize the whole revenue system: transaction value, transaction volume, gross margin, seller capacity, partner leverage, implementation burden, retention, and expansion probability.")}${cards(d.ecosystem,"four")}</section>
 <section class="pursuit-section shell"><div class="assumptions"><h3>My 1,000 assumptions, and the 100 potential things I may be wrong about</h3><p>This is intentionally not presented as inside knowledge. In the first 30 days, I would replace public assumptions with customer conversations, usage data, win-loss evidence, pipeline conversion, implementation economics, product input, and field feedback.</p><div class="assumption-grid">${d.assumptions.map(x=>`<div><b>${esc(x.title)}</b>${esc(x.text)}</div>`).join("")}</div></div></section>
 <section id="interview" class="pursuit-section shell"><div class="interview-box"><div><div class="pursuit-kicker">WHY I AM PURSUING THIS ROLE</div><h2>I build the commercial path from capability to production and expansion.</h2><p>${esc(d.interview)}</p><div class="pursuit-grid two" style="margin-top:25px">${d.fit.map((x,i)=>`<div class="pursuit-card" style="min-height:145px"><span class="overline">${String(i+1).padStart(2,"0")}</span><p style="margin-top:18px">${esc(x)}</p></div>`).join("")}</div></div><div class="interview-action"><a href="mailto:spiegelman.connor@gmail.com?subject=${subject}">Interview Connor about ${esc(d.company)}</a></div></div></section>
 <section class="pursuit-section shell">${sectionHead("SOURCES REVIEWED","Public evidence behind the thesis","These links support the company, product, role, customer, and target-account observations. Strategic recommendations are my interpretation and should be validated internally.")}<div class="source-list">${d.sources.map(x=>`<a class="source-link" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)} ↗</a>`).join("")}</div><p class="source-note">No customer, partner, territory, pipeline, roadmap, or pricing status should be inferred beyond what the linked public sources explicitly state.</p></section>
 </main><footer class="footer"><div class="footer-inner shell"><span>Connor Spiegelman · Business Development · Partnerships · Enterprise AI GTM</span><a href="mailto:spiegelman.connor@gmail.com">spiegelman.connor@gmail.com</a></div></footer>`;
}
function renderVideos(){
 document.title="Private Pursuit Video Scripts | Connor Spiegelman";
 const order=["assort","perplexity","listen","scale","sierra","anthropic","cursor"];
 return `<header class="pursuit-topbar"><div class="shell"><a class="pursuit-brand" href="index.html">CONNOR SPIEGELMAN<small>CI FLOW · RECORDING ROOM</small></a><div class="pursuit-status">Private recording scripts<br>25 August 2026</div></div></header><main class="video-library shell"><div class="pursuit-role"><span>7 COMPANY THESES</span><span>VIDYARD</span><span>~3 MINUTES EACH</span></div><h1 style="font-size:clamp(46px,7vw,88px);line-height:.94;letter-spacing:-.055em;margin:24px 0">Record the thesis, not a cover letter.</h1><p class="pursuit-lead">Use the company page as the screen share. Speak naturally, keep the account example concrete, and end by asking to interview so you can replace public assumptions with internal evidence.</p><div class="assumptions" style="margin-top:35px"><h3>Recording rules</h3><div class="assumption-grid"><div><b>Open with the commercial claim</b>No biography before the thesis.</div><div><b>Show one account</b>A strategic logo makes the thinking tangible.</div><div><b>Do not pretend to know internals</b>Name the assumptions and invite correction.</div><div><b>Keep the ask narrow</b>Ask to interview and pressure-test the work.</div></div></div>${order.map(k=>{const d=window.PURSUITS[k];return `<article class="video-script"><div class="timing">${esc(d.role)} · ${esc(d.company)}</div><h2>${esc(d.company)}</h2>${d.video.map(x=>`<h3>${esc(x.time)} · ${esc(x.label)}</h3><p>${esc(x.text)}</p>`).join("")}<div class="delivery">Delivery note: do not read this word for word. Keep the structure, use your own phrasing, and point to the relevant visual or account section while speaking.</div></article>`}).join("")}</main><footer class="footer"><div class="footer-inner shell"><span>Connor Spiegelman · Private pursuit scripts</span><a href="mailto:spiegelman.connor@gmail.com">spiegelman.connor@gmail.com</a></div></footer>`;
}
const app=document.getElementById("pursuit-app"); if(!app)return;
const key=document.body.dataset.pursuit;
if(key==="videos")app.innerHTML=renderVideos();
else if(window.PURSUITS&&window.PURSUITS[key])app.innerHTML=renderPage(key,window.PURSUITS[key]);
else app.innerHTML='<main class="shell" style="padding:80px 0"><h1>Thesis not found.</h1></main>';
document.querySelectorAll('[data-segment-switcher]').forEach(sw=>{const buttons=[...sw.querySelectorAll('[data-segment]')],panels=[...sw.querySelectorAll('[data-panel]')];buttons.forEach(btn=>btn.addEventListener('click',()=>{const i=btn.dataset.segment;buttons.forEach(x=>x.classList.toggle('active',x===btn));panels.forEach(x=>x.classList.toggle('active',x.dataset.panel===i));}));});
})();